site_name: Simple Backups
site_url: https://luiscberrocal.github.io/simple-backups
repo_url: https://github.com/luiscberrocal/simple-backups
repo_name: luiscberrocal/simple-backups
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings:
      watch:
        - simple-backups
extra:
  social:
    - icon: fontawesome/brands/twitter
      # replace with your own tweet link below
      link: https://github.com/luiscberrocal/cookiecutter-pypackage
      name: Tweet
    - icon: fontawesome/brands/facebook
      # replace with your own facebook link below
      link: https://github.com/luiscberrocal/cookiecutter-pypackage
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/luiscberrocal/simple-backups
      name: Github
    - icon: material/email
      link: "mailto:luis.berrocal.1942@gmail.com"
  # to enable disqus, uncomment the following and put your disqus id below
  # disqus: disqus_id
# uncomment the following and put your google tracking id below to enable GA
#google_analytics:
  #- UA-xxx
  #- auto
