site_name: Simple Backups
site_url: https://luiscberrocal.github.io/simple-backups
repo_url: https://github.com/luiscberrocal/simple-backups
repo_name: luiscberrocal/simple-backups
#strict: true
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - API: api.md
theme:
  name: material
  language: en
  #logo: assets/logo.png
  palette:
    scheme: preference
    primary: indigo
    accent: indigo
  # features:
  #   - navigation.indexes
  #   - navigation.instant
  #   - navigation.tabs.sticky
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings
extra:
  social:
    - icon: fontawesome/brands/twitter
      # FIXME replace with your own tweet link below
      link: https://github.com/luiscberrocal/cookiecutter-pypackage
      name: Tweet
    - icon: fontawesome/brands/facebook
      # FIXME replace with your own facebook link below
      link: https://github.com/luiscberrocal/cookiecutter-pypackage
      name: Facebook
    - icon: fontawesome/brands/github
      link: https://github.com/luiscberrocal/simple-backups
      name: Github
    - icon: material/email
      link: "mailto:luis.berrocal.1942@gmail.com"
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
copyright: |
  &copy; 2023 <a href="https://github.com/luiscberrocal/simple-backups" targe="_blank" rel="noopener">Luis C. Berrocal</a>
